services:
  server:
    build: server
    entrypoint: 
      - java
      - -jar
      - /app.jar
      # - -agentlib:jdwp=transport=dt_socket,server=y,address=*:5005
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
    ports:
      - "8210:8080"
      # Enable port for debugging
      - "8000:8000"
    depends_on:
      - database
      - keycloak
  
  webapp:
    build: webapp
    ports: 
      - "8209:4200"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports: 
      - 8211:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8211
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HOSTNAME_DEBUG=true
    volumes:
      - ./realms:/opt/keycloak/data/import
    command: start-dev --import-realm
  
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=very_safe_password
      - POSTGRES_DB=deck-ranking

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
